defaultPortal: developer-test-account-1
portals:
  - name: developer-test-account-1
    portalId: 147139614
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COTe9JGiMxIxQlNQMl8kQEwrAiQACAkCAQ8BAwgPAQEBAgECAQIBDQMKAQIDBxALAQEBASQCHAFbARie2JRGIOmrnigo7ukMMhQQn7_gxVK0fvTpqd3d6PtkGfm6xjrQAUJTUDJfJEBMKwJiABATBgAGAB0AAQABAAEASQABAAcAGgABABAADAABAA8AAQABAAEAAQALAAEAAwABAAEABAAFAAEAAQABAAEABAABAAUAAQABAAEACAABAAYAAgADAAEAEAAEAA8AAQAIAAQAAQABAAEAAQABAAQAAQAFAAEAEgAJAAMAAQAKAAEAAQABAAEAAQABAAEAAQAfAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABADcACgABAAcAFwABAEIAGgABADkBAQBCFPm8rjJQ7fO_O3f426O0SClorbsiSgNldTFSAFoAYAFo6aueKHAAeAA
        expiresAt: '2025-10-26T20:37:06.580Z'
    accountType: DEVELOPER_TEST
    personalAccessKey: >-
      CiRldTEtNmJhMy1hZjI3LTRjNjktOTVlOS0xOWRkZTU0NDBhNjgQntiURhjpq54oKhkABeaRgl2YFSe4Fn9rhwOFUW-AYDak0IZRSgNldTE
    parentAccountId: 147134396
